.TH gtkhx 1 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH tiger
tiger \- A TI-92 Emulator
.SH SYNOPSIS
.B tiger [options]
.SH DESCRIPTION

.B tiger
is a TI-92 Emulator
.SH OPTIONS
.B -c <config file>
Uses config file specified
.PP
.B -r <rom file>
Uses rom file specified

.SH SEE ALSO
None
.SH AUTHOR
This manual page was written by Misha Nasledov <misha@nasledov.com>
